microsoft/ntosebpfext

include/ebpf_ntos_hooks.h, libs/store_helper/user/ebpf_store_helper_um.vcxproj, libs/store_helper/user/packages.config, ntosebpfext/sys/ntosebpfext.vcxproj, ntosebpfext/sys/packages.config, ntosebpfext/user/ntosebpfext_user.vcxproj, ntosebpfext/user/packages.config, scripts/initialize_repo.ps1, scripts/setup_build/packages.config, scripts/setup_build/setup_build.vcxproj, tests/ntosebpfext_unit/ntosebpfext_unit.vcxproj, tests/ntosebpfext_unit/packages.config, tools/export_program_info/export_program_info.vcxproj, tools/export_program_info/packages.config, tools/process_monitor/packages.config, tools/process_monitor/process_monitor.vcxproj
This pull request primarily involves updating the eBPF-for-Windows package from version 0.15.1 to 0.16.0 across multiple project files. Additionally, there is a minor change in the `include/ebpf_ntos_hooks.h` file to modify the condition for defining `EBPF_HELPER`.
Updates to eBPF-for-Windows package:
* `libs/store_helper/user/ebpf_store_helper_um.vcxproj`, `ntosebpfext/sys/ntosebpfext.vcxproj`, `ntosebpfext/user/ntosebpfext_user.vcxproj`, `scripts/setup_build/setup_build.vcxproj`, `tests/ntosebpfext_unit/ntosebpfext_unit.vcxproj`, `tools/export_program_info/export_program_info.vcxproj`, and `tools/process_monitor/process_monitor.vcxproj`: Updated the import project path to reflect the new version of the eBPF-for-Windows package. …
=> Switch to 0.16.0

.github/workflows/cicd.yml
This pull request primarily includes changes to the CI/CD workflow configuration in the `.github/workflows/cicd.yml` file. The key change is the re-enabling of the `process_monitor` job, which was previously disabled due to an issue.
* [`.github/workflows/cicd.yml`](diffhunk://#diff-6727e33ccc9195d67f0786e1384f8f1cdaf4090c3e77547943105bd2b28c99d0L72-R83): The `process_monitor` job has been re-enabled in the CI/CD workflow. It was previously disabled due to an issue, which has now been resolved. The `pre_test` command has been updated to use version `0.16.0` of `Install-eBpfForWindows.ps1`.
CI/CD
No.
No.
=> Add test for process_monitor.exe tool

tools/process_monitor/Test-ProcessMonitor.ps1
This pull request includes a change to the `Test-ProcessMonitor.ps1` script in the `tools/process_monitor` directory. The modification removes the check for an empty output file, `process_monitor_output.txt`. Previously, if the output file was empty, the script would output a message and exit with a status of 1. With this change, the script will proceed to check for the process name in the output file, even if the file is empty.
CI/CD
No.
No.
=> Fix test failure due to empty line at start of process_monitor_output.txt

libs/ebpf_ext/ebpf_ext_drv.c
This pull request includes a change in the `libs/ebpf_ext/ebpf_ext_drv.c` file that modifies the definition of `EBPF_EXT_DEVICE_NAME`. Previously, this macro was defined as a static string. The change introduces a new macro, `EBPF_EXT_DEVICE_NAME_TEMPLATE`, which takes a provider name as a parameter and constructs the device name string. This allows for more flexibility in naming devices. The `EBPF_EXT_DEVICE_NAME` macro now uses this template macro to define its value.
CI/CD
No.
No.
=> Derive device name from PROVIDER_NAME

.github/workflows/cicd.yml, tests/neteventebpfext/netevent_sim/netevent_npi_client.h, tests/neteventebpfext/netevent_sim/netevent_sim.vcxproj, tests/neteventebpfext/netevent_sim/netevent_sim.vcxproj.filters, tests/neteventebpfext/netevent_sim/packages.config
This pull request includes a change in the `.github/workflows/cicd.yml` file. The change modifies the `pre_test` command under `jobs:` to use a new path for the `Install-eBpfForWindows.ps1` script. This script is now located in the `.\bin\process_monitor.Tests\win-x64 directory.
CI/CD
No.
No.
=> Fix ODR violation

tests/process_monitor.Tests/ProcessMonitorTests.cs, tools/process_monitor.Library/ProcessMonitorBPFLoader.cs, tools/process_monitor_bpf/process_monitor.c
Previously we were limited to a few hundred characters for command lines.  This isn't long enough in many cases - such as `cl.exe` compiler invocations that have long include paths on them.  This uses the new support in 0.17 to help with marshaling long strings, so I allow up to 32k characters now which I believe is the maximum possible on Windows because `UNICODE_STRING` has a `USHORT MaximumLength` and that is the byte count, so character count is "max USHORT / 2" or 32k.
Added a test that verifies a process with very long arguments (>5k characters) comes through as expected.
No docs need updated AFAIK.
No installer impact.
=> Add support for very long command lines in ntosebpfext process data

ebpf_extensions/ntosebpfext/ntos_ebpf_ext_process.c, include/ebpf_ntos_hooks.h, tests/ntosebpfext/ntosebpfext_unit/ntos_ebpfext_unit.cpp, tools/process_monitor.Library/ProcessMonitorBPFLoader.cs, tools/process_monitor_bpf/process_monitor.c
Originally when `ntosebpfext` was created, there was a pretty low limit on the number of characters that could be marshalled through, so the strings from the kernel were converted to UTF-8 to pack more characters into the limited space.  But, with the recent PR (#76), we're now able to marshal much longer strings.  Rather than convert them to UTF-8, only to re-convert back to UTF-16 in user mode in many cases, we just pass the UTF-16 string the whole way through.
This reduces 2 string allocations during process create events as a happy little perf side-effect.
I ran the existing tests locally.
No doc updates needed.
No installer impact.
=> Change ntosebpfext command lines and image file names from UTF-8 to UTF-16

.github/workflows/cicd.yml, CONTRIBUTING.md, Directory.Packages.props, ebpf_extensions/neteventebpfext/netevent_ebpf_ext_event.c, ebpf_extensions/neteventebpfext/sys/neteventebpfext.vcxproj, ebpf_extensions/neteventebpfext/sys/packages.config, ebpf_extensions/neteventebpfext/user/neteventebpfext_user.vcxproj, ebpf_extensions/neteventebpfext/user/packages.config, ebpf_extensions/ntosebpfext/ntos_ebpf_ext_process.c, ebpf_extensions/ntosebpfext/sys/ntosebpfext.vcxproj, ebpf_extensions/ntosebpfext/sys/packages.config, ebpf_extensions/ntosebpfext/user/ntosebpfext_user.vcxproj, ebpf_extensions/ntosebpfext/user/packages.config, scripts/initialize_repo.ps1, scripts/setup_build/packages.config, scripts/setup_build/setup_build.vcxproj, tests/neteventebpfext/netevent_sim/netevent_sim.vcxproj, tests/neteventebpfext/netevent_sim/packages.config, tests/neteventebpfext/neteventebpfext_unit/neteventebpfext_unit.vcxproj, tests/neteventebpfext/neteventebpfext_unit/packages.config, tests/ntosebpfext/ntosebpfext_unit/ntosebpfext_unit.vcxproj, tests/ntosebpfext/ntosebpfext_unit/packages.config, tools/netevent_ebpf_ext_export_program_info/netevent_ebpf_ext_export_program_info.vcxproj, tools/netevent_ebpf_ext_export_program_info/packages.config, tools/netevent_monitor/netevent_monitor.vcxproj, tools/netevent_monitor/packages.config, tools/ntos_ebpf_ext_export_program_info/ntos_ebpf_ext_export_program_info.vcxproj, tools/ntos_ebpf_ext_export_program_info/packages.config, tools/process_monitor_bpf/packages.config, tools/process_monitor_bpf/process_monitor_bpf.vcxproj
This pull request includes several updates to dependencies and enhancements to context management in the `ebpf_extensions` module. The most important changes include updating the `eBPF-for-Windows` package version, adding support for context headers, and refactoring context structures for better clarity and functionality.
* Updated `eBPF-for-Windows` package version from `0.17.0` to `0.18.0` in multiple files, including `.github/workflows/cicd.yml`, `CONTRIBUTING.md`, `Directory.Packages.props`, `ebpf_extensions/neteventebpfext/sys/neteventebpfext.vcxproj`, and `ebpf_extensions/neteventebpfext/user/neteventebpfext_user.vcxproj`. [[1]](diffhunk://#diff-6727e33ccc9195d67f0786e1384f8f1cdaf4090c3e77547943105bd2b28c99d0L80-R80) [[2]](diffhunk://#diff-6727e33ccc9195d67f0786e1384f8f1cdaf4090c3e77 …
=> Switch to ebpf 0.18.0 and add supports_context_header

scripts/Install-Extension.ps1, tools/nuget/nuget.proj
1. Added install script for neteventebpfext and ntosebpfext.
2. Added necessary netevetebpfext/ntosebpfext files to nuget package.
CI/CD ran successfully
N/A
N/A
=> add install script for netevetebpfext and ntosebpfext

Directory.Build.props, tools/netevent_monitor/netevent_monitor.vcxproj, tools/process_monitor_bpf/process_monitor_bpf.vcxproj
This pull request focuses on centralizing the Clang executable path configuration and updating the project files to use this new configuration. The main changes include defining a new property for the Clang executable path and updating the build commands to use this property.
Configuration updates:
* [`Directory.Build.props`](diffhunk://#diff-9da24614831c308827a1ae533ffea392c97638c261dd42bd0f5226baa136d16eR19-R21): Added a new property `ClangExec` to define the path to the Clang executable.
Build command updates:
* [`tools/netevent_monitor/netevent_monitor.vcxproj`](diffhunk://#diff-67ce0f27f1eb3b87531d5c5bddc78f4fd2b10a961c2420f4a8a7f6690af84490L164-R164): Modified the build command to use the new `ClangExec` property for compiling `netevent_monitor.c`.
* …
=> Centralize which version of clang to use

global.json
This change updates to the latest patch version for the .NET SDK which contains the latest security fixes.
Note that even though global.json does configure rollForward, roll forward will allow for the build to pass when using a different SDK. 
CI in many cases installs exactly what is in the global.json, so making sure that your build requires the latest patch version ensures that CI is compliant with those vulnerabilities.
CI/CD
NA
NA
=>  Update .NET SDK to latest patch version

.github/workflows/reusable-build.yml, CONTRIBUTING.md, Directory.Build.props, ebpf_extensions/neteventebpfext/sys/neteventebpfext.vcxproj, ebpf_extensions/neteventebpfext/user/neteventebpfext_user.vcxproj, ebpf_extensions/ntosebpfext/sys/ntosebpfext.vcxproj, ebpf_extensions/ntosebpfext/user/ntosebpfext_user.vcxproj, scripts/setup_build/packages.config, scripts/setup_build/setup_build.vcxproj, tests/neteventebpfext/netevent_sim/netevent_sim.vcxproj, tests/neteventebpfext/neteventebpfext_unit/neteventebpfext_unit.vcxproj, tests/ntosebpfext/ntosebpfext_unit/ntosebpfext_unit.vcxproj, tools/netevent_ebpf_ext_export_program_info/netevent_ebpf_ext_export_program_info.vcxproj, tools/netevent_monitor/netevent_monitor.vcxproj, tools/ntos_ebpf_ext_export_program_info/ntos_ebpf_ext_export_program_info.vcxproj, tools/onebranch/onebranch.vcxproj, tools/process_monitor_bpf/process_monitor_bpf.vcxproj, tools/utils/utils.vcxproj, wdk.props
This pull request includes several changes primarily focused on updating project dependencies and configurations. The most significant changes involve the addition of new SDK and WDK packages, updates to project properties, and modifications to include directories and dependencies in various project files.
* Added multiple `Microsoft.Windows.SDK.CPP` and `Microsoft.Windows.WDK` packages to `scripts/setup_build/packages.config` to ensure compatibility with the latest Windows SDK and WDK versions.
* Imported `wdk.props` in `Directory.Build.props` and updated the `AdditionalIncludeDirectories` to use `$(WdkContentRoot)` and `$(WindowsTargetPlatformVersion)`. [[1]](diffhunk://#diff-9da24614831c308827a1ae533ffea392c97638c261dd42bd0f5226baa136d16eR7) …
=> Switch to nuget WDK

ebpf_extensions/neteventebpfext/netevent_ebpf_ext_event.c, tests/neteventebpfext/netevent_sim/netevent_npi_client.h, tests/neteventebpfext/netevent_sim/netevent_npi_provider.h
Fixes #173 by adding separate header structure for netevent that does not depend on ebpf header.
=> Fix netevent header structure

Directory.Packages.props
This pull request includes updates to the `Directory.Packages.props` file to upgrade several package versions. The most important changes are the version updates for the Microsoft.Extensions.Logging and MSTest packages.
Package version updates:
* [`Microsoft.Extensions.Logging.Abstractions`](diffhunk://#diff-5baf5f9e448ad54ab25a091adee0da05d4d228481c9200518fcb1b53a65d4156L14-R18): Updated from version 8.0.0 to 9.0.0.
* [`Microsoft.Extensions.Logging.Console`](diffhunk://#diff-5baf5f9e448ad54ab25a091adee0da05d4d228481c9200518fcb1b53a65d4156L14-R18): Updated from version 8.0.0 to 9.0.0.
* [`Microsoft.NET.Test.Sdk`](diffhunk://#diff-5baf5f9e448ad54ab25a091adee0da05d4d228481c9200518fcb1b53a65d4156L14-R18): Updated from version 17.9.0 to 17.12.0.
* …
=> Update .NET test packages

scripts/onebranch/Nuget.config, scripts/onebranch/pre-build.ps1
This pull request includes changes to the `scripts/onebranch` directory to improve the configuration and initialization process. The most important changes include adding a new `Nuget.config` file and updating the `pre-build.ps1` script to handle errors during repository initialization.
Configuration updates:
* [`scripts/onebranch/Nuget.config`](diffhunk://#diff-5e9e0d4958b664c5fadda650d499ca5762c306cd75c919b1edaa80da938eac82R1-R11): Added a new `Nuget.config` file to configure the package sources for the project.
Initialization script improvements:
* [`scripts/onebranch/pre-build.ps1`](diffhunk://#diff-201f8696433b57790b5086ecc8a95609ea467b0e18ba2882361c1015bc1ca90bR10-R16): Updated the script to copy the `Nuget.config` file and added error handling to provide a clear error message if …
=> Add nuget.config to root when building on onebranch

ebpf_extensions/neteventebpfext/netevent_ebpf_ext_event.c, ebpf_extensions/neteventebpfext/netevent_ebpf_ext_event.h, include/ebpf_netevent_hooks.h, tests/neteventebpfext/netevent_sim/netevent_npi_client.h, tests/neteventebpfext/netevent_sim/netevent_npi_provider.h, tests/neteventebpfext/netevent_sim/netevent_sim.c, tests/neteventebpfext/netevent_sim/netevent_types.h, tests/neteventebpfext/neteventebpfext_unit/netevent_ebpfext_unit.cpp
Added logic to handle capture type as an attach option provided by the attaching client. The capture type specifies the type of events that would be reported.
Unit tests added to test attaching options.
NA
NA
=> Add attach opts to netevent ext

scripts/onebranch/post-build.ps1, tools/nuget/nuget.proj
This change:
* Modifies the post-build script to copy the unsigned nupkgs to the packages subdirectory under build\bin\<arch>. This directory is monitored by internal pipelines to publish nuget packages.
* Updates the name of the core package to include the configuration in the generated name, for non-release configurations. eg. eBPF-for-Windows.Extensions.x64 for the "Release" configuration and eBPF-for-Windows.Extensions.Debug.x64 for the "Debug" configuration.
Internal pipelines were run and confirmed to publish the packages as expected
=> Organize nupkgs for publishing

Directory.Build.props, ebpf_extensions/neteventebpfext/netevent_ebpf_ext_event.c, include/ebpf_netevent_hooks.h, libs/ebpf_ext/ebpf_ext_hook_provider.c, tests/neteventebpfext/netevent_sim/netevent_npi_client.h, tests/neteventebpfext/netevent_sim/netevent_sim.c, tests/neteventebpfext/neteventebpfext_unit/netevent_ebpfext_unit.cpp
- Changing all push locks to spin locks on the code path that invokes netevent programs so that they can be invoked at dispatch IRQL. Closes #200 
- Put clang path under quotes to fix build issues due to spaces in clang path.
For testing the netevent ext , netevent_sim driver invokes the program in a DPC. DPC runs at Dispatch IRQL. Modified netevent_sim to invoke program in a ThreadedDPC which runs at passive IRQL by default. Also raised IRQL to dispatch periodically to ensure invocation is tested at both IRQLs. 
NA
NA
=> Switch push locks to spin lock

ebpf_extensions/neteventebpfext/netevent_ebpf_ext_event.c, ebpf_extensions/neteventebpfext/netevent_ebpf_ext_program_info.h, ebpf_extensions/ntosebpfext/ntos_ebpf_ext_process.c, include/ebpf_netevent_hooks.h, scripts/setup_build/packages.config, tests/neteventebpfext/netevent_sim/netevent_sim.c, tests/neteventebpfext/netevent_sim/netevent_types.h, tests/neteventebpfext/neteventebpfext_unit/netevent_ebpfext_unit.cpp, tools/netevent_monitor/bpf/netevent_monitor.c, wdk.props
The context passed to netevent BPF programs previously only included start and end pointers. This PR introduces additional data_meta field to the context. Also the netevent_sim now simulates pktmon_netevt events.
Changes Made in the PR:
- The pktmon_netevt structures are now published in WDK 10.0.26100.2454. The WDK version has been updated to ensure the correct WDK NuGet package is installed.
- Logic has been added in netevent.c to convert the flat buffer it receives into a context structure, where the data_meta points to start of the buffer and data_start points to the packet payload.
Refactored simulator code and existing tests to test modified changes.
NA
NA
=> Modify netevent ctx

.github/workflows/cicd.yml, CONTRIBUTING.md, Directory.Packages.props, ebpf_extensions/neteventebpfext/netevent_ebpf_ext_event.c, ebpf_extensions/neteventebpfext/netevent_ebpf_ext_program_info.h, ebpf_extensions/neteventebpfext/sys/neteventebpfext.vcxproj, ebpf_extensions/neteventebpfext/user/neteventebpfext_user.vcxproj, ebpf_extensions/ntosebpfext/ntos_ebpf_ext_process.c, ebpf_extensions/ntosebpfext/ntos_ebpf_ext_program_info.h, ebpf_extensions/ntosebpfext/sys/ntosebpfext.vcxproj, ebpf_extensions/ntosebpfext/user/ntosebpfext_user.vcxproj, ntosebpfext.props, scripts/Install-eBpfForWindows.ps1, scripts/initialize_repo.ps1, scripts/setup_build/packages.config, scripts/setup_build/setup_build.vcxproj, tests/neteventebpfext/netevent_sim/netevent_sim.vcxproj, tests/neteventebpfext/neteventebpfext_unit/netevent_ebpfext_unit.cpp, tests/neteventebpfext/neteventebpfext_unit/neteventebpfext_unit.vcxproj, tests/ntosebpfext/ntosebpfext_unit/ntosebpfext_unit.vcxproj, tools/netevent_ebpf_ext_export_program_info/netevent_ebpf_ext_export_program_info.vcxproj, tools/netevent_monitor/netevent_monitor.vcxproj, tools/ntos_ebpf_ext_export_program_info/ntos_ebpf_ext_export_program_info.vcxproj, tools/nuget/nuget.proj, tools/process_monitor.Library/process_monitor.Library.csproj, tools/process_monitor_bpf/process_monitor_bpf.vcxproj
- Added a new ntosebpfext.props to add vcxproj definitions
- Updated ebpf-for-windows version to 0.21
- Removed PROG_TYPE and ATTACH_TYPE and replaced with consuming ebpf_structs.h (as they were moved there)
- Update program info capabilities to consume the 0.21 breaking change
- Add missing attach params validation in neteventext
Updates to neteventext unit tests to validate attach params.
n/a
n/a
=> Update ntosebpfext to consume ebpf v0.21.0

tools/nuget/ebpf-for-windows.extensions.props, tools/nuget/nuget.proj
Add .props file for auto-import and include path update. Enables auto-update of consuming project's `AdditionalIncludeDirectories` so manual update isn't necessary.
Resolves #219
Built package, consumed in external project, verified no extra code was needed to update include path.
N/A
N/A
=> Add .props file in NuGet package for auto-import and include path update

.github/workflows/reusable-build.yml, scripts/onebranch/post-build.ps1, scripts/onebranch/pre-build.ps1, tools/nuget/nuget.proj
This change has the following:
- Updates the pre_build step to copy the Install-Extension.ps1 script into the build output folder, to allow for build processing
- Updates logic in the post_build step to ensure that we are pulling from the proper binaries
- Updates the nuget package to utilize the post-processed Install-Extension.ps1 script
=> Update Onebranch packaging for internal build pipeline

ebpf_extensions/neteventebpfext/netevent_ebpf_ext_event.c
Removed spin lock guard around event_buffer operations by replacing it with per-cpu event buffers.
Closes #206 
NA
NA
NA
=> Remove spin lock

Directory.Build.props, scripts/setup_build/packages.config, wdk.props
Bumping WDK version to match ebpf-for-windows repo (https://github.com/microsoft/ebpf-for-windows/commit/b2babceba564fea80a2b8296869801b9473a7e85)
This pull request updates the Windows SDK and WDK package versions across the build configuration to `10.0.26100.4204`, and introduces a workaround for a known issue with the WDK NuGet package. It also updates the `usersim` submodule to a newer commit.
**Build configuration and dependency updates:**
* Updated all references to the Windows SDK and WDK packages in `scripts/setup_build/packages.config` to version `10.0.26100.4204`, removing older versions.
* Changed the `WDKVersion` property in `wdk.props` to `10.0.26100.4204` to match the new package version.
**Workaround for WDK NuGet package issue:**
* Added the `DriverCatalog_Enable` property …
=> Update WDK from 10.0.26100.2454 to 10.0.26100.4204
